# Generated by Django 2.1.2 on 2018-11-18 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20181118_2038'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyID',
            fields=[
                ('surveyID', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer not to specify')], default='N', max_length=1)),
                ('status', models.CharField(choices=[('S', 'Student'), ('W', 'Working'), ('R', 'Retired')], default='W', max_length=1)),
                ('investment', models.CharField(choices=[('H', 'I prefer higher reward and I am willing to tolerate higher risk'), ('L', 'I prefer relatively stable although the potential reward will be lower as well')], default='H', max_length=1)),
                ('combination', models.CharField(choices=[('S', 'Pure Stocks'), ('B', 'Pure Bonds'), ('M', 'Stocks and Bonds')], default='M', max_length=1)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
