# Generated by Django 2.1.2 on 2018-11-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181118_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyid',
            old_name='userID',
            new_name='user',
        ),
    ]
