# Generated by Django 2.1.2 on 2018-11-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20181125_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioid',
            name='portfolioName',
            field=models.CharField(default='filler', max_length=15),
        ),
        migrations.AlterField(
            model_name='stockid',
            name='companyName',
            field=models.TextField(default='filler'),
        ),
        migrations.AlterField(
            model_name='stockid',
            name='tickerID',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
