# Generated by Django 2.1.2 on 2018-11-25 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20181125_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('dateTest', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
