# Generated by Django 2.1.2 on 2018-11-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_tester_datetest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tester',
            name='firstName',
        ),
        migrations.AddField(
            model_name='tester',
            name='assetPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tester',
            name='assetReturn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tester',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='ticker',
            field=models.CharField(default='null', max_length=5),
        ),
    ]
