# Generated by Django 2.1.2 on 2018-11-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20181125_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='date',
            field=models.DateField(),
        ),
    ]
