# Generated by Django 2.1.2 on 2018-11-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20181125_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockid',
            name='ipoDate',
        ),
    ]
