# Generated by Django 2.1.3 on 2018-11-28 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_stockid_ipodate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioid',
            name='goalValue',
        ),
        migrations.RemoveField(
            model_name='portfolioid',
            name='timeHorizon',
        ),
    ]
